### ISSUE TITLE
Netlify errorType":"Runtime.UnhandledPromiseRejection

### ISSUE THREAD

**Issue by eduf** [QingWei-Li/notea#11]
Hi,

I'm a journalist testing Notea so that I can recommend to my readers.
I've tried the netlify option and it didin't work for me.
https://edufnotes.netlify.app/

Error message bellow.

How can I fix it?

Best

`{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'byteLength' of undefined","trace":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'byteLength' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:314:20)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}`

**Comment by QingWei-Li** [comment]
Please check whether the bucket has been manually created

**Comment by eduf** [comment]
Sorry. I tried once again (following your instructions at the repo) and it failed again. So I just deleted it. More than that I am not able to answer to you. Thanks for the great effort. It seems that the product is not for me right now. Good look and thanks again.

**Comment by QingWei-Li** [comment]
It working for me https://notea-demo.netlify.app/
If you want to keep trying, I can help, I want to make it easier to use.
No matter what, thank you for coming.
