### ISSUE TITLE
Problems with chrome 

### ISSUE THREAD

**Issue by K0IN** [QingWei-Li/notea#111]
I tested my self-hosted (version latests) notea on 3 devices with chrome and every one gets stuck with "website not responding".
It is not reproducible with the example page or a clean one, so I think there is a problem with one of my posts?
The same behaviour did NOT apply to Edge(chromium) or Firefox -> the site works as intended 
I also cleaned all local data, but I'm still running into endless loading and the "not responding" error

![image](https://user-images.githubusercontent.com/19688162/135749254-df7ec85f-9652-4022-9b21-7bb88c1cfa72.png)
after some point i run in out of memory exception
![image](https://user-images.githubusercontent.com/19688162/135749296-e0c02a32-042e-4085-926d-fc5c8a15ac60.png)

**Comment by QingWei-Li** [comment]
Are you using the latest version?

Please check the storage. Dev Tools -> Application -> Store
![image](https://user-images.githubusercontent.com/7565692/136305825-a30b494d-4f92-4efc-a954-3ef3b7cd4601.png)

**Comment by K0IN** [comment]
Seems to be fixt in the new Chrome update. 

Google Chrome | 95.0.4638.69 (Official Build) (64-bit)
