### ISSUE TITLE
[Docker] Failed to load tree?

### ISSUE THREAD

**Issue by BrodyStone21** [QingWei-Li/notea#119]
Hey all, trying to get this set up and I'm sure I'm doing something wrong.

I copied the docker run command and changed the `STORE_END_POINT` variable to `localhost` and attempted to run the container.

I can login to the Web UI, however, I get a red "Failed to load tree" error pop up.

Below you can find my docker run command. Do I need to change the default access and secret key? I just copied them from the command.

```
docker run -d \
  --name notea \
  -p 3000:3000 \
  -e STORE_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F \
  -e STORE_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG \
  -e STORE_BUCKET=notea \
  -e STORE_END_POINT=localhost \
  -e STORE_FORCE_PATH_STYLE=true \
  -e PASSWORD=Password123 \
  -e COOKIE_SECURE=false \
  cinwell/notea
```

I'm trying to run this on my local network. I'd like to avoid using a reverse proxy or generating any kind of certificates. Not sure if this is possible though.

**Comment by monoxane** [comment]
I'm also getting this error after updating mine in k8s the other day.

**Comment by airtonix** [comment]
@QingWei-Li can you please provide a working `docker-compose.yml` that will get notea running with minio ?

**Comment by airtonix** [comment]
update... found this link... maybe it works: 

https://github.com/QingWei-Li/notea/issues/67#issuecomment-909897665

**Comment by everydaylearner** [comment]
does anyone has a working docker-compose.yml file? would you please share it?

**Comment by vineethmn** [comment]
This one works for me

services:
  notea-webapp:
    image: cinwell/notea
    container_name: notea-webapp
    ports:
      - "3000:3000"
    environment:
      - STORE_ACCESS_KEY=raspberry
      - STORE_SECRET_KEY=raspberry
      - STORE_BUCKET=notea
      - STORE_END_POINT=http://notea-db:9002
      - STORE_FORCE_PATH_STYLE=true
      - PASSWORD=raspberry
      - COOKIE_SECURE=false
      - BASE_URL="http://192.168.137.128:3000/"
  notea-db:
    image: minio/minio
    container_name: notea-db
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=raspberry
      - MINIO_ROOT_PASSWORD=raspberry
    volumes:
      - /mnt/data:/data
    command: server /data --console-address ":9001"

**Comment by BrodyStone21** [comment]
Closing this because I stopped trying to use Notea a few months ago.

**Comment by BrodyStone21** [comment]
Closing this because I stopped trying to use Notea a few months ago.

**Comment by acourter27** [comment]
If anyone else is having this problem locally, without minio, the access keys in the question are the S3 IAM creds. You'd have to configure the bucket, permissions, and IAM role/creds before setting this up.

The app can run locally without a cert, but you're still storing notes in S3 so everything is transmitting. 

The "tree" it's referring to is a file stored in S3 that helps the program know how to display the notes.
