### ISSUE TITLE
Can't fetch my images from S3, but upload works fine

### ISSUE THREAD

**Issue by lajlev** [QingWei-Li/notea#19]
![image](https://user-images.githubusercontent.com/133836/116873160-7d385080-ac17-11eb-9f1b-3d6e5ba94c60.png)
![image](https://user-images.githubusercontent.com/133836/116873240-a0630000-ac17-11eb-80d2-d2498cc8d918.png)

Any clue?

**Comment by QingWei-Li** [comment]
Fixed via https://github.com/QingWei-Li/notea/commit/78360e1b9cab5636001ff01c44e7b79816f64736

Please sync repo.
