### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by billyjacoby** [QingWei-Li/notea#2]
After entering the (correct) password the login page just reloads and asks again for the password.

I see it creates documents in my Minio instance, but i cant get further than this.

**Comment by dnelw** [comment]
I had the same issue and ended up solving it by setting the `COOKIE_SECURE` environment variable to false and `BASE_URL` to the proper base_url my instance was hosted at.

**Comment by QingWei-Li** [comment]
If the website is not HTTPS, you need to set `COOKIE_SECURE ` to false.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies
