### ISSUE TITLE
When using outside of network, Images not working

### ISSUE THREAD

**Issue by diamkil** [QingWei-Li/notea#28]
a bit of investigation got me to the /api/file/... url which actually return the local minio url instead of the Image.. this should be fixed

**Comment by QingWei-Li** [comment]
You should allow external networks to access your MinIO.
Access to `api/file` will redirect to the file signature URL of MinIO.

**Comment by diamkil** [comment]
I don't think it should be that way. All my databases like MySQL, InfluxDB are local only and I'd put Notea the same way if this would be fixed

**Comment by QingWei-Li** [comment]
First of all, this is not a bug. Binary files such as images are usually stored on the hard disk of the server or S3. It is common practice to return the url of the file on the backend.

Secondly, if the server returns pictures, there are some disadvantages.

The file will be read twice(Minio to server, server to client), halving the efficiency

It will take up memory when reading files, and crash if there are too many requests at the same time

I can add an environment variable about reading files internally, if you still insist.

**Comment by diamkil** [comment]
Would love to have the option. Your arguments are right but I personally will be using the other way
