### ISSUE TITLE
Unable to see uploaded images in posts

### ISSUE THREAD

**Issue by pmobbe** [QingWei-Li/notea#29]
Been using Notea since I first saw it being mentioned on Reddit and thinks it is a great app. 

One thing that I can't get around though is that I can upload images just fine but Notea will not render them. 

This is my setup. 

Notea is running in Docker and is behind my NAS reverse proxy. I access Notea using a URL that I have a SSL certificate for (https://notes.<mydomain>.com). This works great. 

I run Minio in a different Docker container and that one too is behind a https URL (https://minio.<mydomain>.com) 

As I said, images are uploading just fine but when Notea tries to go and fetch the image it gets a 403 back from the server and not the temporary redirect (307). 

There is nothing in the log about this error.

If I take the URL that Notea is trying to load and paste that directly into the browser  an error message from Minio comes up saying that the signature of the request isn't correct. 

I have tried to have Notea access my Minio store using a http URL and then I get the redirect (307) but since my Notea app is running under https the browser will not allow the http call. 

Any help is appreciated. 

Thanks,

**Comment by QingWei-Li** [comment]
I previously got a problem of directly accessing the signed url generated by MinIO and prompting a wrong signature 403.
Later I learned that my nginx server configuration was missing the host header.
```nginx
server {
 listen 80;
 server_name example.com;
 location / {
   proxy_set_header Host $http_host;
   proxy_pass http://localhost:9000;
 }
}
```

I'm not sure what problem you got, you need to tell me more.

**Comment by pmobbe** [comment]
Here are the relevant section from my nginx.conf that is my reverse proxy.

    add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload" always;

    location / {

        proxy_connect_timeout 60;
        proxy_read_timeout 60;
        proxy_send_timeout 60;
        proxy_intercept_errors off;
        proxy_http_version 1.1;

        proxy_set_header        Upgrade            $http_upgrade;
        proxy_set_header        Connection            $connection_upgrade;
        proxy_set_header        Host            $http_host;
        proxy_set_header        X-Real-IP            $remote_addr;

        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto            $scheme;

        proxy_pass http://localhost:19122;
    }
    
 Everything except the retrieving the images works. 
 Im on a Mac (Catalina)
 Tried Safari as well as Chrome. 
 Running with the latest Minio image from Docker Hub (2021-04-22)
 
 here is the error message if I click on the generated link for the image in a browser.
 
 ```
 <Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
<Key>files/2021/05/06/8e9a237f.png</Key>
<BucketName>notea</BucketName>
<Resource>/notea/files/2021/05/06/8e9a237f.png</Resource>
<RequestId>167C850FA23DD26B</RequestId>
<HostId>b2dedb5d-8ccd-4c45-8dd1-8fa60bab6e67</HostId>
</Error>
```

**Comment by QingWei-Li** [comment]
Check MinIO document https://docs.min.io/docs/setup-nginx-proxy-with-minio.html Maybe you are missing something
