### ISSUE TITLE
Cannot Check/Uncheck Boxes on Firefox

### ISSUE THREAD

**Issue by tomershvueli** [QingWei-Li/notea#32]
Not sure what's happening here, but on Firefox I'm not able to check or uncheck check boxes on notes where on Chrome it's working perfectly fine.

**Comment by QingWei-Li** [comment]
https://github.com/outline/rich-markdown-editor/issues/431

**Comment by tommoor** [comment]
You need to remove prosemirror-transform `1.3.2` from yarn.lock, the editor is not compatible with this version:

https://github.com/QingWei-Li/notea/blob/main/yarn.lock#L5735

**Comment by RavetcoFX** [comment]
latest version still has this happening
