### ISSUE TITLE
oracle 免费额度存储S3试了下，似乎不行？ 500 Internal Server Error.

### ISSUE THREAD

**Issue by molezz** [QingWei-Li/notea#34]
.env 新建后修改如下，id和密钥用省略号
```  
STORE_ACCESS_KEY=7e1e5………………4ee2
STORE_SECRET_KEY=pni3q6X……………………VY=
STORE_BUCKET=zzbucket
STORE_END_POINT=https://自己name.compat.objectstorage.ap-chuncheon-1.oraclecloud.com
PASSWORD=123123
STORE_REGION=ap-chuncheon-1
# STORE_FORCE_PATH_STYLE=
```

**Comment by QingWei-Li** [comment]
https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

> ```js
> s3 = new AWS.S3({
>  region: 'us-ashburn-1',
>  endpoint: 'https://' + mynamespace + '.compat.objectstorage.us-ashburn-1.oraclecloud.com',
>  accessKeyId: 'gQ4+YC530sBa8qZI6WcbUbtH8oar0exampleuniqueID',
>  secretAccessKey: '7fa22331ebe62bf4605dc9a42aaeexampleuniqueID',
>  s3ForcePathStyle: true,
>  signatureVersion: 'v4',
>});
>```

Equal to

```env
STORE_ACCESS_KEY=YC530sBa8qZI6WcbUbtH8oar0exampleuniqueID
STORE_SECRET_KEY=7fa22331ebe62bf4605dc9a42aaeexampleuniqueID
# Required
STORE_FORCE_PATH_STYLE=true
STORE_BUCKET=mynamespace
PASSWORD=123
STORE_REGION=us-ashburn-1
STORE_END_POINT='https://' + mynamespace + '.compat.objectstorage.us-ashburn-1.oraclecloud.com'
```

**Comment by molezz** [comment]
试成功了
不需单引号
bucket是buecket名不是namespace
更新文档

**Comment by Dikko3506** [comment]
how to get 
STORE_ACCESS_KEY=7e1e5………………4ee2
STORE_SECRET_KEY=pni3q6X……………………VY=

with oracle
