### ISSUE TITLE
Linking between notes

### ISSUE THREAD

**Issue by RavetcoFX** [QingWei-Li/notea#39]
Ability to link between notes manualy/automatically would be great to allow for functionality similar to obsidian notes / Zettelkasten

**Comment by cannibalox** [comment]
bi-directionnal links would be great (also show links to pages pointing to the current page)

**Comment by QingWei-Li** [comment]
`0.2.0` is released


https://user-images.githubusercontent.com/7565692/120912959-13074580-c6c6-11eb-8609-75c65d5f9512.mp4

**Comment by RavetcoFX** [comment]
Holy crap :o incredible thanks @QingWei-Li
