### ISSUE TITLE
direct file system support

### ISSUE THREAD

**Issue by Shagon94** [QingWei-Li/notea#4]
The databases mentioned are S3 compatible, having an direct file system support gives you the ability to only run one image and still have the functionality of the package.

reasons for the feature:
- easier management of files
- smaller system requirements
- allows the user to use any file system for storing the data.

Example:
- having direct file system functionality allows the user to just point to a single folder on their machine and be done with it
- some tools such as typora.io already have this when all they need to work with markdown files is just to create them in a folder

Given the above I really love the tool itself, having the feature to use the filesystem itself instead of S3 might prove useful for NAS and laptop users where they run the tools they need on said machine.

**Comment by QingWei-Li** [comment]
Thanks for the suggestion.

My original intention to make this product is to use it anytime, anywhere. I have also used offline note-taking applications, such as the typora.io you mentioned or directly use vscode. But it's not enough to check at anytime, if I don't sync data or don't bring my machine.

I need to control my own data and take notes anywhere, so I made it.

**Comment by diamkil** [comment]
> The databases mentioned are S3 compatible, having an direct file system support gives you the ability to only run one image and still have the functionality of the package.
> 
> reasons for the feature:
> 
> * easier management of files
> * smaller system requirements
> * allows the user to use any file system for storing the data.
> 
> Example:
> 
> * having direct file system functionality allows the user to just point to a single folder on their machine and be done with it
> * some tools such as typora.io already have this when all they need to work with markdown files is just to create them in a folder
> 
> Given the above I really love the tool itself, having the feature to use the filesystem itself instead of S3 might prove useful for NAS and laptop users where they run the tools they need on said machine.

Once I'm done with my final exams (I'm using Notea to take my notes by the way) I plan to learn to make a docker image with multiple services in it and make one with MinIO in the same image as Notea. This wouldn't change the code but would allow to  use one image with one docker path set for everything

**Comment by diamkil** [comment]
@QingWei-Li @Shagon94 https://github.com/diamkil/docker-notea take a look at this. Will be publishing to docker hub soon once I'm done with the readme
