### ISSUE TITLE
Import/Export .md files

### ISSUE THREAD

**Issue by themedleb** [QingWei-Li/notea#5]
I have more than thousand .md files but no idea how to import them to switch to Notea.
And would be really awesome to be able to export all my .md files in one click (maybe all compressed in a zip file).

**Comment by diamkil** [comment]
If you use MinIO you could add them in there manually and download them. Just remove the .md and it should work (I think)
I know it works for downloading, not sure for uploading

**Comment by jamesscottbrown** [comment]
This doesn't quite work for uploading: the imported files are searchable, and can be viewed by manually editing the URL, but they do not appear in the list of notes in the pane on the left, as they are not recorded in the `tree` file.

It would be useful to have a way to regenerate the `tree` file by re-indexing the S3 bucket.
