### ISSUE TITLE
API Security Gap

### ISSUE THREAD

**Issue by arjunrbery** [QingWei-Li/notea#51]
The API endpoint for images doesn't check for the user to be logged in. If someone shares a note and later unshares the note, but the image was opened in a new tab, it can still be accessed from the user history.

**Comment by QingWei-Li** [comment]
The signature of the image resource is valid for 7 days.
Can it solve the problem, if it is allowed to set the expiration time for the sharing page?

**Comment by arjunrbery** [comment]
Hey QuingWei-Li,

I've spun up a demo. For example, if I wanted to grab an image to save back locally or print that was shared, it would visit the following link. That link now resides in my history and can be visited even when not signed in. The S3 signature link will regenerate every time because I am visiting the API link.

Link visited: https://notea-test.vercel.app/api/file/2021/05/11/0ff51a3b.png

Thank you,
Arjun Bery

**Comment by arjunrbery** [comment]
I pushed a temp fix to my fork. The change protects the files from being accessed without being logged in but prevents the files from being seen when the page is shared.
