### ISSUE TITLE
[Feature Request] Store notes on non-S3 Backend

### ISSUE THREAD

**Issue by ModdedGamers** [QingWei-Li/notea#59]
I love this project, but I don't want to deal with the overhead of running an S3 server alongside this. Would it be possible to make it so that notes are stored in a human-readable file format directly on the file system? Such as a directory of .md files?

**Comment by almereyda** [comment]
Next to a file system backend, other viable options can be:

- https://remotestorage.io/
- https://solidproject.org/

which both offer nice ways to bring a filesystem to the web with providing simple primitives for storing JSON-via-HTTP client side, and also provide user authentification for multi-tenancy.

Further examples can be found at https://0data.app/

**Comment by QingWei-Li** [comment]
https://github.com/QingWei-Li/notea#why-not-use-filesystem-storage

**Comment by Valiantiam** [comment]
I know also it's not a solution, but MinIO is actually really well documented and easy to install/run if you don't want to have a separate "offsite" S3 bucket.

**Comment by ModdedGamers** [comment]
That's what I mean. I don't want to run minio alongside this. it's just another thing to run and administrate and keep secure.

**Comment by Valiantiam** [comment]
I think the desire is understood and the feedback is welcome, but I think the feature is outside the scope of the focus/design mentality of this project. There are many other solutions out there that do have a direct file backend or DB backend. 

I wont speak for @QingWei-Li but it's my opinion this FR and others like it should be marked "Wont fix".
