### ISSUE TITLE
Info/Warning/Tip notices not rendering correctly in public view

### ISSUE THREAD

**Issue by Twisterado** [QingWei-Li/notea#60]
Hi, thank you so much for this awesome project!
For some reason, the notices aren't rendering correctly in the public view.

Here is an example side by side (public on the left, obviously):
![notea_notices_not_working](https://user-images.githubusercontent.com/28116938/118773942-94b54180-b885-11eb-8eec-b96ee0b47723.png)

I hope this is just a small rendering issue, so it may be easy to fix?
Please let me know if you need any further information, e.g. to reproduce the issue.

**Comment by QingWei-Li** [comment]
Missing style in sharing page. I will fix it in the few days.
