### ISSUE TITLE
Any documentation on hosting locally on a LXC or bare metal server?

### ISSUE THREAD

**Issue by ithakaa** [QingWei-Li/notea#62]
Looking for a note taking app I can self host, do we have documentation for shelf hosting?

**Comment by QingWei-Li** [comment]
It is easy to install via docker, as mentioned in the documentation. https://github.com/QingWei-Li/notea#docker

**Comment by ithakaa** [comment]
> It is easy to install via docker, as mentioned in the documentation. https://github.com/QingWei-Li/notea#docker

I'm.not looking for host it in a blocked.
Any chance we can get documentation ?

**Comment by QingWei-Li** [comment]
Do you mean to run the app service directly on your server?

Maybe you need to install NodeJS and clone the repo on your machine. 
Next create `.env` file in the repo directory https://github.com/QingWei-Li/notea#storage
Compile code via `yarn && yarn build`
Run service via `yarn start`

**Comment by ithakaa** [comment]
> Do you mean to run the app service directly on your server?
> 
> Maybe you need to install NodeJS and clone the repo on your machine.
> Next create `.env` file in the repo directory https://github.com/QingWei-Li/notea#storage
> Compile code via `yarn && yarn build`
> Run service via `yarn start`

I'm so so sorry to keep pestering you. 
I'm not a developer or experienced Linux guru
If you can help with a small readme, it would be really good

**Comment by QingWei-Li** [comment]
Don't you consider deploying to vercel or netilfy? This is the easiest and most efficient way.


Click the button [![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/git/external?repository-url=https%3A%2F%2Fgithub.com%2FQingWei-Li%2Fnotea&env=STORE_ACCESS_KEY,STORE_SECRET_KEY,STORE_BUCKET,STORE_END_POINT,STORE_FORCE_PATH_STYLE,PASSWORD)

Then set the environment variable refer to this [example](https://github.com/QingWei-Li/notea#docker) The premise is that you have an s3 storage service and know how to find these values.


![image](https://user-images.githubusercontent.com/7565692/119126980-4f039f00-ba66-11eb-914a-49525bed8789.png)

**Comment by ithakaa** [comment]
> Don't you consider deploying to vercel or netilfy? This is the easiest and most efficient way.
> 
> Click the button [![Deploy with Vercel](https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e)](https://vercel.com/new/git/external?repository-url=https%3A%2F%2Fgithub.com%2FQingWei-Li%2Fnotea&env=STORE_ACCESS_KEY,STORE_SECRET_KEY,STORE_BUCKET,STORE_END_POINT,STORE_FORCE_PATH_STYLE,PASSWORD)
> 
> Then set the environment variable refer to this [example](https://github.com/QingWei-Li/notea#docker) The premise is that you have an s3 storage service and know how to find these values.
> 
> ![image](https://user-images.githubusercontent.com/7565692/119126980-4f039f00-ba66-11eb-914a-49525bed8789.png)

I would honestly like to host it on my local home network.
Sorry for the trouble
