### ISSUE TITLE
Feature Request: provide option for Article Width?

### ISSUE THREAD

**Issue by resettarget** [QingWei-Li/notea#68]
Qingwei, 
Thanks for making notea. 

Would you consider to support customizable article width? Something like 'double width' or even 'user input width value'. That's something like Notion's 'Full Width'. 

Reason is, when I paste a relative 'big' picture or many times, write long code/words, a wider article makes it easy to read. Thanks

**Comment by trogit90** [comment]
This would also be very nice for tables aswell if you want alot of information in a table you don't want to scroll sideways. 
Thanks for an amazing piece of software tho! can't wait to start using it!

**Comment by trogit90** [comment]
After latest update tables are gone? can't find it anymore when doing /

**Comment by QingWei-Li** [comment]
@trogit90 fixed in `v0.2.4`
