### ISSUE TITLE
outliner app capabilities in future plans?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [QingWei-Li/notea#7]
something like workflowy (nested bullets) baked into this app might be cool to gain extra traction / popularity. this is definitely already much nicer, it seems to me, than the evernote desktop app. keep up the great work!

so far notea looks real nice! really nice! it's up there as far as i'm concerned with [Logseq](https://logseq.com/) and [Obsidian](https://obsidian.md/).

**Comment by QingWei-Li** [comment]
I researched and decided not to do this feature.
Outliner app is another style of note-taking app different from markdown note. If it needs to be implemented, I have to rewrite the editor. My initial idea was to make a pure markdown note app. 
Maybe I will consider two-way quoting in the future. I think this will be more useful.
