### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by diminou91** [QingWei-Li/notea#77]
Hi there,

I wanted to try out notea to see if it fits my needs, everything is (or seems to be) set up correctly.

I get "Incorrect password" on login, even though it is the correct one.

Logs are throwing :
```
  name: 'API_ERR_INVALID_CSRF_TOKEN',,
{,
  message: 'Invalid CSRF token',,
  stack: 'API_ERR_INVALID_CSRF_TOKEN: Invalid CSRF token\n' +,
  status: 401,,
    '    at APIError.throw (/app/.next/server/chunks/841.js:163:19)\n' +,
    '    at Array.useCsrf (/app/.next/server/chunks/841.js:93:49)\n' +,
    '    at loop (/app/node_modules/next-connect/dist/index.cjs:69:47)\n' +,
    '    at next (/app/node_modules/next-connect/dist/index.cjs:74:13)\n' +,
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
    '    at /app/node_modules/next-iron-session/dist/index.js:137:7\n' +,
}
```

Any idea to help me with this ? :)
Thanks!

**Comment by QingWei-Li** [comment]
Do you disable cookies?

**Comment by diminou91** [comment]
No, I'm using the basic conf : 
`STORE_SECRET_KEY=
STORE_BUCKET=notea
STORE_END_POINT=http://localhost:9000
# Required
STORE_FORCE_PATH_STYLE=true
PASSWORD=`

**Comment by QingWei-Li** [comment]
You can try to clone the project and run it locally.

**Comment by diminou91** [comment]
Same issue.

I'm running minio on another machine, and it is not secure (no valid certs), could this be the culprit ?

Thanks

**Comment by QingWei-Li** [comment]
Have you set the PASSWORD? It is required.

**Comment by diminou91** [comment]
Haha, yes I did! :)
I've even tried different ones juste to make sure one char was not the culprit. Reverted back to "notea" but still "invalid password" and the same issue.

**Comment by QingWei-Li** [comment]
Is your website https? If not, you need to set `COOKIE_SECURE=false`.

**Comment by diminou91** [comment]
Ha, that was it!
Thanks for you help :) I was reading the readme again and again and I missed it everythime... sorry :D

**Comment by QingWei-Li** [comment]
No problem. 

I updated the example in the reamde, it should be clearer now.
