### ISSUE TITLE
ToDo broken?

### ISSUE THREAD

**Issue by dominikpflegerl** [QingWei-Li/notea#86]
When I created a ToDo list, I am not able to tick the checkboxes. 

Neither on mobile (Google Chrome) or on Desktop (Google Chrome and Firefox).
I've seen ticked checkboxes in the live demo, but there I can't tick or untick it either.

**Comment by QingWei-Li** [comment]
I tested it on the demo and it working for me.

https://user-images.githubusercontent.com/7565692/125875587-5ddc6f79-6291-408d-9c60-cc4507d1650d.mp4

**Comment by dominikpflegerl** [comment]
I was wrong, it somehow now works in Google Chrome on Android, but I figured it out. 
The browser extension for my password manager Enpass causes this issue. 

That's why it also didn't work in Firefox, which is my secondary browser, and it's only installed extension is Enpass.

But how can it be that a password manager extension causes such a weird behaviour?

**Comment by QingWei-Li** [comment]
I have no idea. Maybe you should report a bug to the Enpass team.
