### ISSUE TITLE
Enable prefix env variable

### ISSUE THREAD

**Issue by mxrlkn** [QingWei-Li/notea#92]
I would like to have notea access s3 under a prefix. I see it's a setting here: https://github.com/QingWei-Li/notea/blob/96a71af55688fbe892ea5b7c0d76fe90e454297e/libs/server/store/index.ts#L4-L12

But it's not enabled.

Can prefix be enabled as an env variable?

**Comment by QingWei-Li** [comment]
Sorry, what is `prefix env variable`? I did not find relevant information.

**Comment by mxrlkn** [comment]
Sorry I mean environment variable.

You pass prefix to `new StoreS3` with an empty string

https://github.com/QingWei-Li/notea/blob/96a71af55688fbe892ea5b7c0d76fe90e454297e/libs/server/store/index.ts#L4

https://github.com/QingWei-Li/notea/blob/96a71af55688fbe892ea5b7c0d76fe90e454297e/libs/server/store/index.ts#L12


Is it possible to be able to change `prefix` to something else via an environment variable?

Like this for example:

```
export function createStore() {
  return new StoreS3({
    accessKey: getEnv('STORE_ACCESS_KEY', undefined, true),
    secretKey: getEnv('STORE_SECRET_KEY', undefined, true),
    endPoint: getEnv('STORE_END_POINT'),
    bucket: getEnv('STORE_BUCKET', 'notea'),
    region: getEnv('STORE_REGION', 'us-east-1'),
    pathStyle: getEnv('STORE_FORCE_PATH_STYLE', false),
    prefix: getEnv('STORE_PREFIX', ''),
  })
}
```

Then I can have notea store the data on a specific path in S3.

**Comment by kdasme** [comment]
Hey @QingWei-Li, thank you for a great tool.

If I understand correctly, @mxrlkn is asking whether it is possible to specify S3 key as a prefix to store the data, so it wouldn't be necessary to create a dedicated bucket for Notea. I actually wanted to ask the same question. :)

**Comment by mxrlkn** [comment]
I just tested it, and it works 🎉

Thank you!
