### ISSUE TITLE
Uncaught DOMException: Quota Exceeded

### ISSUE THREAD

**Issue by MattieX** [QingWei-Li/notea#98]
## Current Setup
* Notea Docker Image with Minio as S3
* Accessing Notea via Caddy Reverse Proxy with no extra headers for isolating this identified bug
* Tested with Latest Updated Version v0.3.5
* Tested in Chrome, Edge & Firefox

## Describing the Issue
When opening numerous pages one after another, eventually a red error with no context will animate and loop at the bottom of the screen as the page continually jumps about -  making typing or viewing notes impossible.
<img width="257" alt="Screenshot 2021-09-02 210820" src="https://user-images.githubusercontent.com/21284075/131910146-3a7d19e8-18c7-47c8-9577-e586e0176a9e.png">

Checking the web console I see the following messages when this happens.
<img width="419" alt="Screenshot 2021-09-02 210620" src="https://user-images.githubusercontent.com/21284075/131910504-311dc231-b92c-4515-848c-8dc9d980c1b2.png">

Googling the issue points to application storage being exceeded - checking the Storage tab when this shows this is the case. Each new page opened seems to almost (but not always) increase this storage quota, sometimes exceeding it.

<img width="283" alt="Screenshot 2021-09-02 210719" src="https://user-images.githubusercontent.com/21284075/131910730-f4cfe7a2-f33b-41f8-989e-7e3bda2aa120.png">

In order to fix this issue I have to Control + Refresh in chrome or to manually clear the cache on the storage tab.

**Comment by QingWei-Li** [comment]
Will there be this problem with `http://ip:3000`? I guess it may be a proxy server configuration issue.

**Comment by MattieX** [comment]
> Will there be this problem with `http://ip:3000`? I guess it may be a proxy server configuration issue.

So I tried binding the container to the host and accessing directly via port 3000, disabled COOKIE_SECURE and you're right, the Storage seems to sit between 1-3MB when moving between pages as opposed to very quickly getting to several hundred MB and hitting the Quota, pointing to a likely reverse proxy issue as you suggest.

However, I'm unsure as to what could be causing this with the reverse proxy, as I access other reverse proxied services fine utilising the same approach as shown below.

---


When using my domain for https the docker-compose for Notea file contains:
```
environment:
  - COOKIE_SECURE=false
  - BASE_URL="https://note.mydomain.com"
  - STORE_ACCESS_KEY=<MINIO_ACCESS_KEY>
  - STORE_SECRET_KEY=<MINIO_SECRET_KEY>
  - STORE_BUCKET=notea
  - STORE_END_POINT="https://s3.mydomain.com"
  - STORE_FORCE_PATH_STYLE=true
  - PASSWORD=<GUI_Password>
```

And using the [Caddy](https://caddyserver.com/docs/quick-starts/reverse-proxy) file in the most common way to access a proxied service, my file contains:
```
note.mydomain.com{
  reverse_proxy 10.10.10.15:3000
  tls /path/to/cert.pem /path/to/privkey.pem
}
```

Do you think this could be an issue regarding the configuration of MINIO for the S3 Storage?

**Comment by QingWei-Li** [comment]
I'm not sure, I use nginx + docker, this is my configuration.

```nginx
# minio.cinwell.com.conf
server  {
	listen	80;
	listen	443 ssl;
    server_name	minio.cinwell.com;
	ssl_certificate	/etc/nginx/ssl/*.cinwell.com.pem;
	ssl_certificate_key	/etc/nginx/ssl/*.cinwell.com.key;

    location / {
		proxy_set_header   Host    $host;
        proxy_pass	http://127.0.0.1:9001;
    }
}
# notea.cinwell.com.conf
server  {
	listen	80;
	listen	443 ssl;
    server_name	notea.cinwell.com;
	ssl_certificate	/etc/nginx/ssl/*.cinwell.com.pem;
	ssl_certificate_key	/etc/nginx/ssl/*.cinwell.com.key;

    location / {
		proxy_set_header   Host    $host;
        proxy_pass	http://127.0.0.1:3001;
    }
}
```

run docker
```
docker run -d \
  --name notea \
  -p 3001:3000 \
  -e STORE_ACCESS_KEY=[] \
  -e STORE_SECRET_KEY=[] \
  -e STORE_BUCKET=notea \
  -e STORE_END_POINT=https://minio.cinwell.com \
  -e STORE_FORCE_PATH_STYLE=true \
  -e IS_DEMO=true \
  cinwell/notea
```

**Comment by MattieX** [comment]
I've tried disabling caddy and setting up a fresh Nginx Docker using your suggested recommendation. However, I'm still seeing the issue after browsing a couple of pages of my notes.

```
events {

}
http {
    server  {
        listen  80;
        listen  443 ssl;
        server_name     note.mydomain.com;
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key     /etc/nginx/ssl/privkey.pem;

        location / {
            proxy_set_header   Host    $host;
            proxy_pass  http://192.168.10.13:3000;
        }
    }
    server  {
        listen  80;
        listen  443 ssl;
        server_name     s3.mydomain.com;
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key     /etc/nginx/ssl/privkey.pem;

        location / {
            proxy_set_header   Host    $host;
            proxy_pass  http://192.168.10.14:9000;
        }
    }
    server  {
        listen  80;
        listen  443 ssl;
        server_name     s3-console.mydomain.com;
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key     /etc/nginx/ssl/privkey.pem;

        location / {
            proxy_set_header   Host    $host;
            proxy_pass  http://192.168.10.14:9001;
        }
    }
}
```

Below is my Minio Docker configuration which I suppose is the last thing that could be causing the issue:
```yaml
version: '3'
services:
    notea-s3:
      restart: always
      image: minio/minio
      container_name: notea-s3
      environment:
        MINIO_ACCESS_KEY: <MINIO_ACCESS_KEY>
        MINIO_SECRET_KEY: <MINIO_SECRET_KEY>
        MINIO_BROWSER_REDIRECT_URL: https://s3-console.mydomain.com
      volumes:
        - ./minio-data:/data
      entrypoint: sh
      expose:
        - 9000
        - 9001
      command: -c 'mkdir -p /data/notea && /usr/bin/minio server /data --console-address :9001 --address :9000'
      networks:
        default:
          ipv4_address: 192.168.10.14
```

**Comment by QingWei-Li** [comment]
Can you reproduce the problem in https://notea.cinwell.com

This is my test result, the cache storage did not increase when opening multiple tabs.

![image](https://user-images.githubusercontent.com/7565692/132266016-2e91d37c-4a10-4883-b573-94c051f04e9e.png)

**Comment by QingWei-Li** [comment]
Previously, image resources were cached in cache storage by default, so I removed this configuration. Now you need to update to `0.3.6`, then manually clear the cache, click `clear site data` button.
